import NavBar from "@/components/NavBar";
import "./globals.css";
import { Rubik } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer/Footer";

// const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-10 pt-10">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
